{
  imports = [
    ../modules/base.nix
    ../modules/alacritty.nix
    ../modules/atuin.nix
    ../modules/btop.nix
    ../modules/eza.nix
    ../modules/fzf.nix
    ../modules/git.nix
    ../modules/neovim.nix
    ../modules/packages-cli.nix
    ../modules/packages-darwin.nix
    ../modules/packages-python.nix
    ../modules/ripgrep.nix
    ../modules/starship.nix
    ../modules/zellij.nix
    ../modules/zoxide.nix
    ../modules/zsh.nix
  ];
}
