name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes

      - uses: extractions/setup-just@v2

      - run: just lint

  nix-build:
    strategy:
      matrix:
        include:
          - runs-on: ubuntu-latest
            nix_path: nixpkgs=channel:nixos-unstable
          - runs-on: macos-latest
            nix_path: nixpkgs=channel:nixpkgs-unstable
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: cachix/install-nix-action@v31
        with:
          nix_path: ${{ matrix.nix_path }}
          extra_nix_config: |
            experimental-features = nix-command flakes

      - uses: extractions/setup-just@v2

      - name: Check flake
        if: matrix.runs-on == 'ubuntu-latest'
        run: just nix-check

      - name: Build full profile
        run: GIT_NAME="test" GIT_EMAIL="test@example.com" just nix-build full

  setup:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Run full setup
        env:
          GIT_NAME: test
          GIT_EMAIL: test@example.com
        run: sh setup.sh full
